# Generated by Django 3.2.12 on 2022-09-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0008_remove_errorlog_document_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='error_line',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='data',
            field=models.TextField(blank=True, help_text='Data when the error happened.', max_length=10, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='data_reference',
            field=models.CharField(blank=True, help_text='Reference to the data, can be id, line. Use line:10 or id:452 to to differ between id|line.', max_length=10, null=True, verbose_name='Reference data'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='data_type',
            field=models.CharField(blank=True, help_text='Data type, can the the model, ex.: models.RawUnpaywall', max_length=255, null=True, verbose_name='Data type'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='error_description',
            field=models.TextField(blank=True, help_text='More context about the error', max_length=255, null=True, verbose_name='Error description'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='error_message',
            field=models.CharField(blank=True, help_text='Message of python error.', max_length=255, null=True, verbose_name='Mensagem de erro'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='error_type',
            field=models.CharField(blank=True, help_text='Type of python error.', max_length=50, null=True, verbose_name='Tipo de erro'),
        ),
    ]
